### ISSUE TITLE
[ERR_MODULE_NOT_FOUND]: Cannot find package 'conf'

### ISSUE THREAD

**Issue by saeedesmaili** [SoCuul/alfred-expressvpn#1]
Thanks for putting this workflow together. I get the following error when trying it after installation:

<img width="995" alt="image" src="https://github.com/user-attachments/assets/ce9641d3-8ffc-4b11-9455-96aa0a636858">

**Comment by SoCuul** [comment]
Hey! I'd recommend using an LTS version of node.js as not all nodejs packages have full compatibility with the latest stable version. I'm personally using v20.10.0, but the latest 20.x.x release should work just fine 😄
